# -*- coding: utf-8 -*-
"""1. Predprocesiranje skupa podataka.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wivmihe0g69MZhVsBQaTpsvUMVcELPS_
"""

import pandas as pd

"""
1. Predprocesiranje skupa podataka

"""

# Određivanje putanje do CSV datoteke
CSV_FILE_PATH = "/content/anime.csv"

# Učitavanje CSV datoteke (provjerite svoje delimiter u csv datoteci), ispis broja redaka i stupaca
df = pd.read_csv(CSV_FILE_PATH, delimiter=',')
print("CSV size before: ", df.shape)

df = df.drop(columns=['Japanese name']) # Brisanje nepotrebnog stupaca (stupac ima znakove koje sql ne prepoznaje)
df = df.dropna() # Brisanje redaka s nedostajućim vrijednostima
print("CSV size after: ", df.shape) # Ispis broja redaka i stupaca nakon predprocesiranja
print(df.head()) # Ispis prvih redaka dataframe-a

# Random dijeljenje skupa podataka na dva dijela 80:20 (trebati će nam kasnije)
df20 = df.sample(frac=0.2, random_state=1)
df = df.drop(df20.index)
print("CSV size 80: ", df.shape)
print("CSV size 20: ", df20.shape)

# Spremanje predprocesiranog skupa podataka u novu CSV datoteku
df.to_csv("anime_PROCESSED.csv", index=False) # Spremanje predprocesiranog skupa podataka u novu CSV datoteku
df20.to_csv("anime_PROCESSED_20.csv", index=False) # Spremanje 20% skupa podataka u novu CSV datoteku